### ISSUE TITLE
DRY out content type

### ISSUE THREAD

**Issue by brookr** [craigcampbell8/gradebook#2]
These conditional just need to set a local var for content type. The res.write doesn't need to be repeated: https://github.com/craigcampbell8/gradebook/blob/master/gradebook-server.js#L21

**Comment by craigaaroncampbell** [comment]
I wrote a function to get the content type. It's a few lines longer overall, but technically DRY since it doesn't repeat the writeHead line.

**Comment by brookr** [comment]
Great! Clean code is better than short code. :]
